// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjrgqzycywylaifkilaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqcmdxenljeXd5bGFpZmtpbGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2ODc2ODEsImV4cCI6MjA1ODI2MzY4MX0.y2AtFwoTE1_XbqqobtlVN4nF1_L0263WxXdNSEvAlK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);